Main page with subpages descriptions
RZEPI/engineering-thesis-vue pull request #10
Opened 2024-12-04 13:20 UTC by RZEPI

2024-12-05 05:15 UTC, grczk requested changes
the same visual issues as on the react repo, please take a look there

2024-12-05 05:43 UTC, grczk requested changes

2024-12-05 05:43 UTC, grczk commented on vue-app/src/components/UI/FeatureDescription.vue
> +    if(isFirst) return;
something is wrong 'cause I can't go back from the second site desc to the first one, isFirst is true

2024-12-07 17:13 UTC, marziel2001 approved these changes
I like this

2024-12-08 07:17 UTC, grczk approved these changes

2024-12-08 12:57 UTC, merged