Add page with animated components
RZEPI/engineering-thesis-vue pull request #13
Opened 2024-12-05 08:07 UTC by grczk

2024-12-05 13:00 UTC, RZEPI requested changes
Style of the page is kinda ugly, there is no margin
input and button also look plain

2024-12-05 13:00 UTC, RZEPI commented on vue-app/src/components/UI/AnimatedComponent.vue
> +});
this should use TypeScript type

2024-12-05 13:00 UTC, RZEPI commented on vue-app/src/router.ts
> +    { path: "/animation", component: AnimationPage },
its better to left NotFound page at the end of route list

2024-12-09 10:32 UTC, RZEPI approved these changes, later dismissed

2024-12-09 10:59 UTC, NOTSAHLO submitted a review, later dismissed

2024-12-10 06:41 UTC, NOTSAHLO approved these changes

2024-12-10 08:31 UTC, RZEPI approved these changes

2024-12-10 08:31 UTC, merged